
import javax.crypto.AEADBadTagException;
import javax.swing.ButtonGroup;
import javax.swing.ButtonModel;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JToggleButton;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author oscar
 */
public class Prestamo extends javax.swing.JFrame {

    /**
     * Creates new form Prestamo
     */
    DefaultTableModel tm = new DefaultTableModel();

    public Prestamo() {
        initComponents();
        String ids[] = { "NoCuotas", "Capital", "Interes", " Seguro de desgravamen", "Saldo", "Seguro Incendios",
                "Valor total de cuota" };
        tm.setColumnIdentifiers(ids);
        // jTable1.setModel(tm);
        jPanel5.setVisible(false);

        jPanel4.setVisible(false);
        jlabelAuto.setVisible(false);
        jlabelCasa.setVisible(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator2 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jSeparator3 = new javax.swing.JSeparator();
        jComboxTipo = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        txtCostoAuto = new javax.swing.JTextField();
        lblDinero = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtPrestamoSoli = new javax.swing.JTextField();
        JComboxMeses = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        tbtFrances = new javax.swing.JToggleButton();
        tbtAleman = new javax.swing.JToggleButton();
        jlabelCasa = new javax.swing.JLabel();
        jlabelAuto = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblCapital = new javax.swing.JLabel();
        lblInteres = new javax.swing.JLabel();
        lblSeguro = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblCuota = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        lblTotalCapital = new javax.swing.JLabel();
        lblTotalInteres = new javax.swing.JLabel();
        lblTotalDesgrav = new javax.swing.JLabel();
        lblTotalAPagar = new javax.swing.JLabel();
        btbTablaAmorti = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1500, 800));

        jPanel1.setPreferredSize(new java.awt.Dimension(1500, 800));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 1843, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(765, 765, 765)
                                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 313,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addContainerGap(765, Short.MAX_VALUE))));
        jPanel3Layout.setVerticalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 46, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 34,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))));

        jComboxTipo.setModel(new javax.swing.DefaultComboBoxModel<>(
                new String[] { "Selecciona un Tipo", "Automotriz", "Hipotecario", "Emergente", "Consumo", " ", " " }));
        jComboxTipo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboxTipoMouseClicked(evt);
            }
        });
        jComboxTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboxTipoActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 51, 204));
        jLabel5.setText("¿QUE TIPO DE CREDITO NECESITAS?");

        jButton1.setText("Calcular");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        lblDinero.setText("¿Cuanto dinero soliticitas?");

        jLabel7.setText("¿En cuantos meses deseas pagarlo?");

        JComboxMeses.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione una fecha",
                "12 meses (1año)", "18 meses (1.5años)", "24 meses (2años)", "30 meses (2.5años)", "36 meses (3años)",
                "42 meses (3.5años)", "48 meses (4años)", "54 meses (4.5años)", "60 meses (5años)" }));
        JComboxMeses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JComboxMesesActionPerformed(evt);
            }
        });

        jLabel8.setText("¿Como quieres pagar tus intereses?");

        tbtFrances.setText("Metodo Frances");
        tbtFrances.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbtFrancesActionPerformed(evt);
            }
        });

        tbtAleman.setText("MetodoAleman");
        tbtAleman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbtAlemanActionPerformed(evt);
            }
        });

        jlabelCasa.setText("¿Cuanto cuesta el la casa?");

        jlabelAuto.setText("¿Cuanto cuesta el auto?");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
                jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel5Layout.createSequentialGroup()
                                                .addGap(23, 23, 23)
                                                .addGroup(jPanel5Layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jlabelCasa)
                                                        .addComponent(jlabelAuto)))
                                        .addGroup(jPanel5Layout
                                                .createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addGroup(jPanel5Layout.createSequentialGroup()
                                                        .addContainerGap()
                                                        .addComponent(txtCostoAuto,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE, 97,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING,
                                                        jPanel5Layout.createSequentialGroup()
                                                                .addGap(20, 20, 20)
                                                                .addComponent(lblDinero))))
                                .addGap(0, 0, Short.MAX_VALUE))
                        .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel5Layout.createSequentialGroup()
                                                .addGap(25, 25, 25)
                                                .addGroup(jPanel5Layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addGroup(jPanel5Layout.createSequentialGroup()
                                                                .addComponent(tbtFrances)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(tbtAleman))
                                                        .addComponent(jButton1)))
                                        .addGroup(jPanel5Layout.createSequentialGroup()
                                                .addGap(43, 43, 43)
                                                .addGroup(jPanel5Layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(JComboxMeses,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel7)
                                                        .addComponent(jLabel8)))
                                        .addGroup(jPanel5Layout.createSequentialGroup()
                                                .addGap(67, 67, 67)
                                                .addComponent(txtPrestamoSoli, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(136, 216, Short.MAX_VALUE)));
        jPanel5Layout.setVerticalGroup(
                jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(jlabelCasa)
                                .addGap(18, 18, 18)
                                .addComponent(jlabelAuto)
                                .addGap(32, 32, 32)
                                .addComponent(txtCostoAuto, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(36, 36, 36)
                                .addComponent(lblDinero)
                                .addGap(18, 18, 18)
                                .addComponent(txtPrestamoSoli, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(78, 78, 78)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(JComboxMeses, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 96,
                                        Short.MAX_VALUE)
                                .addComponent(jLabel8)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(tbtFrances)
                                        .addComponent(tbtAleman))
                                .addGap(55, 55, 55)
                                .addComponent(jButton1)
                                .addGap(145, 145, 145)));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("LOS PAGOS MENSUALES SERAN DE ");

        jLabel3.setText("Detalle de credito");

        lblCapital.setText("x");

        jLabel1.setText("+");

        jLabel4.setText("+");

        lblCuota.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N

        jLabel6.setText("Capital: ");

        jLabel9.setText("Total Interes:");

        jLabel10.setText("Total Seguro Desgravamen:");

        jLabel11.setText("Total a pagar:");

        btbTablaAmorti.setText("Mostrar tabla de amortizacion");
        btbTablaAmorti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btbTablaAmortiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
                jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel4Layout.createSequentialGroup()
                                                .addGap(331, 331, 331)
                                                .addComponent(jLabel2))
                                        .addGroup(jPanel4Layout.createSequentialGroup()
                                                .addGap(283, 283, 283)
                                                .addComponent(lblCapital, javax.swing.GroupLayout.PREFERRED_SIZE, 59,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(43, 43, 43)
                                                .addComponent(jLabel1)
                                                .addGap(44, 44, 44)
                                                .addGroup(jPanel4Layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(lblCuota)
                                                        .addGroup(jPanel4Layout.createSequentialGroup()
                                                                .addComponent(lblInteres,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 54,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(
                                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addGroup(jPanel4Layout.createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addGroup(jPanel4Layout.createSequentialGroup()
                                                                                .addComponent(jLabel4)
                                                                                .addGap(37, 37, 37)
                                                                                .addComponent(lblSeguro,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                        66,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                        .addGroup(jPanel4Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.TRAILING,
                                                                                false)
                                                                                .addComponent(lblTotalInteres,
                                                                                        javax.swing.GroupLayout.Alignment.LEADING,
                                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                        67, Short.MAX_VALUE)
                                                                                .addComponent(lblTotalCapital,
                                                                                        javax.swing.GroupLayout.Alignment.LEADING,
                                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                        Short.MAX_VALUE))))))
                                        .addGroup(jPanel4Layout.createSequentialGroup()
                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel3)
                                                .addGap(147, 147, 147))
                                        .addGroup(jPanel4Layout.createSequentialGroup()
                                                .addGap(275, 275, 275)
                                                .addGroup(jPanel4Layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING,
                                                                false)
                                                        .addComponent(jLabel9)
                                                        .addComponent(jLabel6)
                                                        .addGroup(jPanel4Layout.createSequentialGroup()
                                                                .addComponent(jLabel11)
                                                                .addGap(91, 91, 91)
                                                                .addComponent(lblTotalAPagar,
                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                        Short.MAX_VALUE))
                                                        .addGroup(jPanel4Layout.createSequentialGroup()
                                                                .addComponent(jLabel10)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(lblTotalDesgrav,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 71,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addGroup(jPanel4Layout.createSequentialGroup()
                                                .addGap(309, 309, 309)
                                                .addComponent(btbTablaAmorti)))
                                .addContainerGap(1602, Short.MAX_VALUE)));
        jPanel4Layout.setVerticalGroup(
                jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel4Layout.createSequentialGroup()
                                                .addGap(59, 59, 59)
                                                .addGroup(jPanel4Layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel1)
                                                        .addComponent(jLabel4))
                                                .addGap(85, 85, 85)
                                                .addComponent(lblCuota)
                                                .addGap(144, 144, 144)
                                                .addComponent(jLabel3)
                                                .addGap(42, 42, 42)
                                                .addGroup(jPanel4Layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel6)
                                                        .addComponent(lblTotalCapital,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE, 16,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(18, 18, 18)
                                                .addGroup(jPanel4Layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel9)
                                                        .addComponent(lblTotalInteres))
                                                .addGap(18, 18, 18)
                                                .addGroup(jPanel4Layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel10)
                                                        .addComponent(lblTotalDesgrav))
                                                .addGap(18, 18, 18)
                                                .addGroup(jPanel4Layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel11)
                                                        .addComponent(lblTotalAPagar)))
                                        .addGroup(jPanel4Layout.createSequentialGroup()
                                                .addComponent(jLabel2)
                                                .addGap(40, 40, 40)
                                                .addGroup(jPanel4Layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(lblCapital)
                                                        .addComponent(lblInteres)
                                                        .addComponent(lblSeguro))))
                                .addGap(41, 41, 41)
                                .addComponent(btbTablaAmorti)
                                .addGap(61, 61, 61)));

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(469, 469, 469)
                                                .addComponent(jLabel5))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(49, 49, 49)
                                                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 50,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(538, 538, 538)
                                                .addComponent(jComboxTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 187,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(509, 509, 509)
                                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(jLabel5)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(49, 49, 49)
                                                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jComboxTipo, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jPanel1Layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jSeparator1,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE, 605,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(1690, 1690, 1690)
                                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 2844, Short.MAX_VALUE));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 2540,
                                javax.swing.GroupLayout.PREFERRED_SIZE));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboxTipoActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jComboxTipoActionPerformed
        String name = (String) jComboxTipo.getSelectedItem();
        switch (name) {
            case "Automotriz":
                jPanel4.setVisible(true);

                jPanel5.setVisible(true);
                jlabelAuto.setVisible(true);
                jlabelCasa.setVisible(false);
                txtCostoAuto.setVisible(true);
                break;
            case "Hipotecario":
                jPanel4.setVisible(true);

                jPanel5.setVisible(true);
                jlabelAuto.setVisible(false);
                jlabelCasa.setVisible(true);
                txtCostoAuto.setVisible(true);
                break;
            case "Emergente":

                jPanel4.setVisible(true);

                jPanel5.setVisible(true);
                jlabelAuto.setVisible(false);
                jlabelCasa.setVisible(false);
                txtCostoAuto.setVisible(false);
                break;
            case "Consumo":
                jPanel4.setVisible(true);

                jPanel5.setVisible(true);
                jlabelAuto.setVisible(false);
                jlabelCasa.setVisible(false);
                txtCostoAuto.setVisible(false);
                break;
            default:
                throw new AssertionError();
        }

    }// GEN-LAST:event_jComboxTipoActionPerformed

    private void jComboxTipoMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_jComboxTipoMouseClicked
        // TODO add your handling code here:
    }// GEN-LAST:event_jComboxTipoMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton1ActionPerformed
        tm.setRowCount(0);
        double montoEntrada = Double.parseDouble(txtPrestamoSoli.getText());
        String mesesEscogidos = (String) JComboxMeses.getSelectedItem();
        String meses = mesesEscogidos.substring(0, 2);
        double mesesEntrada = Double.parseDouble(meses);
        String metodo = elegirMetodo();
        switch (metodo) {
            case "Frances":

                PrestamoUno p1 = new PrestamoUno(montoEntrada, mesesEntrada);
                String capital = String.valueOf(Math.round(p1.calcularAmortizacionPeriodo() * 100.0) / 100.0);
                lblCapital.setText(capital);
                String interes = String.valueOf(p1.calcularInteresPeriodo());
                lblInteres.setText(interes);
                String segurosTotal = String.valueOf(p1.sumarSeguros());
                lblSeguro.setText(segurosTotal);
                lblCuota.setText(String.valueOf(p1.calcularCuotaFija()));
                lblTotalCapital.setText(String.valueOf(montoEntrada));
                Amortizacion am = new Amortizacion();
                am.mostrarTablaFrancesa(montoEntrada, mesesEntrada);
                double Intereses = am.sumarIntereses();
                double TotalDesgrav = am.sumarSeguroDesravamen();
                double totalAPagar = Intereses + TotalDesgrav + montoEntrada;
                lblTotalInteres.setText(String.valueOf(Intereses));
                lblTotalDesgrav.setText(String.valueOf(am.sumarSeguroDesravamen()));
                lblTotalAPagar.setText(String.valueOf(totalAPagar));
                break;
            case "Aleman":
                PrestamoDos p2 = new PrestamoDos(montoEntrada, mesesEntrada);
                String capitalAleman = String.valueOf(Math.round(p2.calcularCapitalFija() * 100.0) / 100.0);
                lblCapital.setText(capitalAleman);
                String interesAleman = String.valueOf(p2.calcularInteres());
                lblInteres.setText(interesAleman);
                String segurosTotalAleman = String.valueOf(p2.sumarSeguros());
                lblSeguro.setText(segurosTotalAleman);
                lblCuota.setText(String.valueOf(p2.calcularCuota()));
                lblTotalCapital.setText(String.valueOf(montoEntrada));
                Amortizacion am2 = new Amortizacion();
                am2.mostrarTablaAleman(montoEntrada, mesesEntrada);
                double InteresesAleman = am2.sumarIntereses();
                double TotalDesgravAleman = am2.sumarSeguroDesravamen();
                double totalAPagarAleman = InteresesAleman + TotalDesgravAleman + montoEntrada;
                lblTotalInteres.setText(String.valueOf(InteresesAleman));
                lblTotalDesgrav.setText(String.valueOf(am2.sumarSeguroDesravamen()));
                lblTotalAPagar.setText(String.valueOf(totalAPagarAleman));
                break;

            default:
                JOptionPane.showMessageDialog(null, "PORFAVRO SELECCIONE UN METODO ");
        }

        /*
         * if(costoAuto == entrada){
         * PrestamoAuto p1 = new PrestamoAuto(entrada, meses);
         * for(int i = 0 ; i<= meses ; i++){
         * tm.addRow(new Object[]{
         * 
         * i,
         * p1.calcularCapital(),
         * 
         * p1.calcularInteres(),
         * p1.calcularSeguroDesgravemen(),
         * p1.saldoTotal(),
         * 
         * p1.calcularSeguroIncendio(),
         * p1.calcularCuotaFrances(),
         * });
         * }
         * }else{
         * PrestamoAuto p1 = new PrestamoAuto(costoAuto, meses, entrada);
         * for(int i = 0 ; i<= meses ; i++){
         * tm.addRow(new Object[]{
         * 
         * i,
         * p1.calcularCapital(),
         * 
         * p1.calcularInteres(),
         * p1.calcularSeguroDesgravemen(),
         * p1.saldoTotal(),
         * 
         * p1.calcularSeguroIncendio(),
         * p1.calcularCuotaFrances(),
         * 
         * });
         * }
         * }
         * 
         * jTable1.setModel(tm);
         */
    }// GEN-LAST:event_jButton1ActionPerformed

    private void JComboxMesesActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_JComboxMesesActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_JComboxMesesActionPerformed

    private void tbtFrancesActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_tbtFrancesActionPerformed
        ButtonGroup bg = new ButtonGroup();
        bg.add(tbtAleman);
        bg.add(tbtFrances);

    }// GEN-LAST:event_tbtFrancesActionPerformed

    private String elegirMetodo() {
        if (tbtAleman.isSelected()) {
            return "Aleman";

        } else if (tbtFrances.isSelected()) {
            return "Frances";
        }
        return "ERROr";
    }

    private void tbtAlemanActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_tbtAlemanActionPerformed

        tbtFrances.setSelected(false);

    }// GEN-LAST:event_tbtAlemanActionPerformed

    private void btbTablaAmortiActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btbTablaAmortiActionPerformed
        double montoEntrada = Double.parseDouble(txtPrestamoSoli.getText());
        String mesesEscogidos = (String) JComboxMeses.getSelectedItem();
        String meses = mesesEscogidos.substring(0, 2);
        double mesesEntrada = Double.parseDouble(meses);
        Amortizacion am = new Amortizacion();
        am.mostrarTablaFrancesa(montoEntrada, mesesEntrada);
        am.setVisible(true);
    }// GEN-LAST:event_btbTablaAmortiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Prestamo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Prestamo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Prestamo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Prestamo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Prestamo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> JComboxMeses;
    private javax.swing.JButton btbTablaAmorti;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboxTipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel jlabelAuto;
    private javax.swing.JLabel jlabelCasa;
    private javax.swing.JLabel lblCapital;
    private javax.swing.JLabel lblCuota;
    private javax.swing.JLabel lblDinero;
    private javax.swing.JLabel lblInteres;
    private javax.swing.JLabel lblSeguro;
    private javax.swing.JLabel lblTotalAPagar;
    private javax.swing.JLabel lblTotalCapital;
    private javax.swing.JLabel lblTotalDesgrav;
    private javax.swing.JLabel lblTotalInteres;
    private javax.swing.JToggleButton tbtAleman;
    private javax.swing.JToggleButton tbtFrances;
    private javax.swing.JTextField txtCostoAuto;
    private javax.swing.JTextField txtPrestamoSoli;
    // End of variables declaration//GEN-END:variables
}
